version: '3.8'

services:
  sam2-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - BEAM_ENDPOINT_URL=${BEAM_ENDPOINT_URL}
    volumes:
      - ./uploads:/app/uploads

  sam2-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
